### ISSUE TITLE
ModuleNotFoundError: No module named 'obstacle_detector'

### ISSUE THREAD

**Issue by iamZhaoHang** [lgkimjy/object_detector#1]
请问作者，'obstacle_detector'是自建的么？

**Comment by lgkimjy** [comment]
@iamZhaoHang No, it is the msg file from [here](https://github.com/tysik/obstacle_detector), it is open-source for detecting certain obstacles. If you want to use my own repository, you should clone [msg](https://github.com/tysik/obstacle_detector/tree/master/msg) to use it.

I have made a similar source by clustering close points to detect multiple people using python. Wish it could help you improve your projects.
